/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_lpai_ldawapper_LDAWapper */

#ifndef _Included_edu_lpai_ldawapper_LDAWapper
#define _Included_edu_lpai_ldawapper_LDAWapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_lpai_ldawapper_LDAWapper
 * Method:    JNI_Train
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_lpai_ldawapper_LDAWapper_JNI_1Train
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     edu_lpai_ldawapper_LDAWapper
 * Method:    JNI_Inference
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_lpai_ldawapper_LDAWapper_JNI_1Inference
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
